language: php
php:
  - 5.6
before_script:
  - composer self-update
  - composer update --prefer-dist || composer update --prefer-source
#  - npm install -g casperjs
#  - phantomjs --version; casperjs --version
#  - grunt connect:test:keepalive & #shooting up a web server for the tests
script:
#  - vendor/bin/phpunit
#  - npm test
#  - rm -v ./vendor/autoload.php ./vendor/composer/!(installed.json)
after_script:
  - vendor/bin/coveralls
cache:
  directories:
    - vendor/
